pre-commit:
  parallel: true
  commands:
    oxlint:
      glob: '*.{js,ts,jsx,tsx}'
      run: bunx oxlint -c oxlint.json --fix {staged_files}
      stage_fixed: true
    oxfmt:
      run: bunx oxfmt --no-error-on-unmatched-pattern {staged_files}
      stage_fixed: true
    build:
      run: bun run build
    # test:
    #   run: bun test --pass-with-no-tests
